name: Build Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string
 
    secrets:
      cr_username:
        required: true
      cr_token:
        required: true
    
env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}

jobs:
  build:
    runs-on: ubuntu-latest #setup ubuntu sebagai server/runner
    steps:
      - #stage checkoutcode
       name: Checkout 
       uses: actions/checkout@v3
      - #atentikasi ke docker registry menggunakan credential
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.cr_username }} 
          password: ${{ secrets.cr_token }}
      - # stage build dan push docker 
       name: Build and push
       uses: docker/build-push-action@v3
       with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pinjammodal/kong:${GITHUB_REF#refs/*/}